### ISSUE TITLE
项目报告

### ISSUE THREAD

**Issue by Eroica-cpp** [Eroica-cpp/DistSearch#18]
@zerolocker @fengwuxing 

项目报告我那部分已经写好了，现在放在了服务器 ~/report/ 文件夹下。
现在已经有30多页了，其实差不多了都。。
现在想到的要加的有：
1. @zerolocker  最后的conclusion要写，让报告完整一点。feature那一部分是不是可以再吹吹？
2. @fengwuxing  你前端的代码整理一下(重命名、去掉注释之类的)，然后简单写个说明。代码追加到后面又可以多十页了。

报告附录的代码我只加了我自己写的部分，你们写的代码写个简单的描述之后整理一下也加进来，整个报告应该可以超过50页。

另外，报告我使用LaTeX生成的，如果你们不熟悉这个环境，把文本发给我就行了。

@zerolocker 这个报告我想除了应付大作业之外，考试完了可以整理一下做成技术手册、完整的说明之类的，放到github上。

以上

**Comment by fengwuxing** [comment]
LaTeX我不熟悉哈，要不这样，我写好我这个部分，用word写，焘哥帮我加进去哈，怎么样？
