### ISSUE TITLE
找个时间出来讨论下一步的计划？

### ISSUE THREAD

**Issue by Eroica-cpp** [Eroica-cpp/DistSearch#19]
RT。
@zerolocker @fengwuxing 什么时候出来讨论一下？
讨论一下接下来做什么之类的，比如:
1. 完善文档
2. 完善用户注册系统
3. 解决很多网页爬不到的问题
4. 能够爬doc, xls的内容

毕竟做了这么多，现在也是半成品了，怎么样也要做完上线吧。

**Comment by fengwuxing** [comment]
我白天上班，正常情况估计要到晚上的八点半才可以回到学校。你们时间怎么安排呢？

**Comment by Eroica-cpp** [comment]
我的时间比较灵活，什么时候都没问题。
看你们的安排咯， @zerolocker 怎么样？

**Comment by zerolocker** [comment]
我也是在实习，要不周末出来？

**Comment by zerolocker** [comment]
对了，为了增进效率，我先把讨论时我想说的列一下：
1、我觉得首要任务是设法让我们的作品能够在Internet上访问
2、其次是解决爬出来的结果没有按照时间排序的问题，解决爬出来的结果只有公文通的问题

**Comment by Eroica-cpp** [comment]
> 我也是在实习，要不周末出来？  

看你们的时间，周末我没问题

> 我觉得首要任务是设法让我们的作品能够在Internet上访问  

现在有nhpcc的服务器(有二级域名下的分页)，但是是win server的，配置solr nutch这些不方便。我觉得还是用原来ubuntu的服务器，然后用iframe或类似的东西链接过去。但是要解决跨域的问题

> 其次是解决爬出来的结果没有按照时间排序的问题，解决爬出来的结果只有公文通的问题  

关于按时间排序，solr本身提供了定制的功能，可能要研究一下。nutch只爬公文通这个很蛋疼。。而且好像只爬了之前用python爬出来的url。。。
