### ISSUE TITLE
solr里面混进了外网链接

### ISSUE THREAD

**Issue by zerolocker** [Eroica-cpp/DistSearch#3]
这是由于第一次nutch爬虫操作的时候没有设置好参数, 导致nutch爬了外网.
现在已经把Nutch里面的外网链接清理完, 但是由于nutch已经把爬的结果送给solr索引了, 所以solr里面有一些外网的东西.

可能重建索引可以解决. 既然李焘安装中文分词功能需要重建索引, 那么刚好.

**Comment by Eroica-cpp** [comment]
是的。
“设置好参数” ，求更新配置文件到github

**Comment by Eroica-cpp** [comment]
@zerolocker @fengwuxing 
明天约个时间去机房：
- [x] 处理中文分词最后一步，重建索引
- [x] 整理服务器上的文件(配置文件，路径等)，在服务器上搭git, 实现服务器、github、我们三个人的PC完全同步
- [x] 商讨下一步（做网站，搭界面）

另外，试一下github的tasklist功能、at人的功能
