### ISSUE TITLE
Nutch不爬公文通

### ISSUE THREAD

**Issue by zerolocker** [Eroica-cpp/DistSearch#4]
我已经设置了conf/regex-urlfilter.txt注释掉这一条规则：
# skip URLs containing certain characters as probable queries, etc.
-[?*!@=]
让它不过滤公文通的网页。
同时也把seed.txt的内容删掉， 只填写一条http://www.szu.edu.cn/board/ ，
让它爬公文通， 它还是不爬。 不知道怎么回事了。

**Comment by zerolocker** [comment]
百度“ nutch 无视robots.txt “　might help.
不过因为我的seed.txt里面只填写了http://www.szu.edu.cn/board/ 并且http://www.szu.edu.cn/board/robots.txt 不存在。 （只存在http://www.szu.edu.cn/robots.txt）
我认为nutch有可能没有看 http://www.szu.edu.cn/robots.txt ，
当然也有可能是因为看了才导致它不愿意爬的。

**Comment by Eroica-cpp** [comment]
这么晚还不睡，辛苦了。
发issue还是好，一水github就看到了

爬不了公文通可能和之前讲的cookie\session设置有关，
不行的话只要找到solr对python的接口，用python爬也行(有现成代码)
现在已知有[SolPython](http://wiki.apache.org/solr/SolPython)，还没仔细看文档

**Comment by Eroica-cpp** [comment]
也可能和ASP.NET的架构有关
这种古老的东西哎。。

**Comment by zerolocker** [comment]
是robots.txt的问题，让nutch无视robots.txt看上去有些麻烦，并且跟session没有关系。 请见notes/LZD_log.md

**Comment by zerolocker** [comment]
Problem solved. See $GITHUB_REPO/notes/LZD_log.md

**Comment by Eroica-cpp** [comment]
great!!
表示给刷屏了

**Comment by zerolocker** [comment]
嘿嘿 不好意思 剩下要做的就是按 ？id=xxx 生成几十万个网址调用nutch去爬了

**Comment by Eroica-cpp** [comment]
服务器campus-search-engine/dedicated-crawler/raw_html/文件夹下的文件目录的是抓好的html文档, 有效id就是那些文件名。用nutch再抓一遍？测试一下速度

**Comment by Eroica-cpp** [comment]
@zerolocker 公文通的url清单已经整理出来了，在服务器$CSE/dedicated-crawlers/url_list.txt里面，直接cat出来然后追加到seed.txt就行了。
