### ISSUE TITLE
最新进展

### ISSUE THREAD

**Issue by Eroica-cpp** [Eroica-cpp/DistSearch#5]
@zerolocker @fengwuxing 

我这几天做了这些事情：
## 1. 公文通爬虫

自己写了一个专门针对公文通的爬虫board_crawler.py（其实只有30-40行代码），代码放在了dedicated-crawlers文件夹下。爬出来的html文档在服务器dedicated-crawlers/raw_html/目录里面，1.1GB, 69575篇有有效内容的公文通(从2002年到昨天)，我想这是能够找到的最全的公文通，2002年之前应该是没有公文通这种东西的。(已知最早的公文通在[这里](http://www.szu.edu.cn/board/view.asp?id=65254))
这些html文档没有上传github,因为github对每个repo有1GB的限制。
### 为什么这么做

这个本来不是计划之内的事情，但是我突然发现只用nutch有些缺陷：
1. 有些东西爬不出来，比如2002年的某篇公文通nutch爬不出来，因为根本没有链接指向它，公文通给的选项最多只有五年的。
2. BFS在这种爬公文通这种事情上效率不高，专用爬虫直接按id爬不用检查重复，BFS爬公文通不知道要检查多少次了。大致看了一下，各个学院的新闻、学校领导信箱等的数据库基本上都是这样设计的，即遍历id就可以了。。

所以，专用爬虫还是有必要的，可以和nutch这种BFS爬虫混合使用。

另外，我的另外两门课：推荐系统、人工智能都能用到这个数据，所以先爬为快了。
最重要的是简单，写这种爬虫也就30分钟工作量;而且自己写的东西，知根知底好维护。。
### 问题和改进
1. 现在爬下来的公文通没有解析，是纯的html文件，这么做的原因就是想利用solr强大的全文检索能力。solr肯定有提供这种接口的（虽然现在只知道对nutch的接口），不然要它何用。。。。我们要想怎么把这些结果和nutch的结果结合起来。
2. 这次遍历了30万个id，单线程的(懒得调了)，历时25个小时左右(主要的时间花在了等待服务器相应，还有无效url的跳转，python的速度完全**不是**瓶颈)。这完全可以用mapreduce模型，虽然很简单，但是起码和并行计算沾边了，演示的时候可以提一提(想想老师说用mapreduce统计词频都能算大作业了。。)。
## 2. 学习用Node.js搭建网站

apache + php + mysql 这种建站方式对于前端小白我来说完全不懂，花了两个小时配置Node.js建了个hello world表示相当激动！后来又看了看D3, bootstrap之类的嵌入node.js毫无压力。 @zerolocker @fengwuxing 如果对linux环境下建站不熟悉的话可以试一下Node.js, 相当简单，[代码在这](https://github.com/Eroica-cpp/Node-notes)。前端的代码还是完全一样的，Node.js相较于apache + php + mysql简化的是服务器端的配置(我觉得是这样的)；你们觉得apache + php + mysql这种方式更好就无视我吧。。
## 其他想说的
1. @fengwuxing 好像在github上不是很活跃？ 求上传建站代码，让小白我学习学习
2. @zerolocker @fengwuxing 周日中午再出来一次如何？

**Comment by zerolocker** [comment]
辛苦了！ 
服务器上的solr打不开了， 提示Could not load core configuration for core collection1. 各有又在上面弄过什么东西吗？

## 

Best regards,
刘卓德
Shenzhen University
Class of 2015
College of Computer Science and Software Engineering

在 2014-06-06 11:56:38，"+Tao Li" notifications@github.com 写道：

@zerolocker@fengwuxing

这几天做了这些事情：
1. 公文通爬虫

自己写了一个专门针对公文通的爬虫board_crawler.py（其实只有30-40行代码），代码放在了dedicated-crawlers文件夹下。爬出来的html文档在服务器dedicated-crawlers/raw_html/目录里面，1.1GB, 53150篇有有效内容的公文通(从2006年到昨天)，我想这是能够找到的最全的公文通，2006年之前要么没有公文通，要么数据已经删除了。
这些html文档没有上传github,因为github对每个repo有1GB的限制。

为什么这么做

这个本来不是计划之内的事情，但是我突然发现只用nutch有些缺陷：
1. 有些东西爬不出来，比如2006年的某篇公文通nutch爬不出来，因为根本没有链接指向它，公文通给的选项最多只有五年的(2006年距今9年了，时间过的真快。。)。
2. BFS在这种爬公文通这种事情上效率不高，专用爬虫直接按id爬不用检查重复，BFS爬公文通不知道要检查多少次了。大致看了一下，各个学院的新闻、学校领导信箱等的数据库基本上都是这样设计的，即遍历id就可以了。。

所以，专用爬虫还是有必要的，可以和nutch这种BFS爬虫混合使用。

另外，我的另外两门课：推荐系统、人工智能都能用到这个数据，所以先爬为快了。
最重要的是简单，写这种爬虫也就30分钟工作量;而且自己写的东西，知根知底好维护。。

问题和改进
现在爬下来的公文通没有解析，是纯的html文件，这么做的原因就是想利用solr强大的全文检索能力。solr肯定有提供这种接口的（虽然现在只知道对nutch的接口），不然要它何用。。。。我们要想怎么把这些结果和nutch的结果结合起来。

这次遍历了30万个id，单线程的(懒得调了)，历时25个小时左右(主要的时间花在了等待服务器相应，还有无效url的跳转，python的速度完全不是瓶颈)。这完全可以用mapreduce模型，虽然很简单，但是起码和并行计算沾边了，演示的时候可以提一提(想想老师说用mapreduce统计词频都能算大作业了。。)。
1. 学习用Node.js搭建网站

apache + php + mysql 这种建站方式对于前端小白我来说完全不懂，花了两个小时配置Node.js建了个hello world表示相当激动！后来又看了看D3, bootstrap之类的嵌入node.js毫无压力。 @zerolocker@fengwuxing 如果对linux环境下建站不熟悉的话可以试一下Node.js, 相当简单，代码在这。前端的代码还是完全一样的，Node.js相较于apache + php + mysql简化的是服务器端的配置(我觉得是这样的)；你们觉得apache + php + mysql这种方式更好就无视我吧。。

其他想说的
@fengwuxing 好像在github上不是很活跃？ 求上传建站代码，让小白我学习学习
@zerolocker@fengwuxing 周日中午再出来一次如何？

**Comment by Eroica-cpp** [comment]
原来的solr文件夹没有动过，我把新的campus-search-engine文件夹整个拷到了服务器上，你是说之前的solr吧。

唯一动过的就是重启了服务器，你看看是不是每次要设置一些东西却没有设置(比如环境变量)

**Comment by zerolocker** [comment]
哦， 我发现了，是在campus-search-engine里面的solr启动失败， 原来的solr可以启动

**Comment by Eroica-cpp** [comment]
ok， 我看看去，可能是文件夹权限设置的问题。
“campus-search-engine里面的solr”在我本机是可以的。

**Comment by Eroica-cpp** [comment]
BTW， @zerolocker 你是不是改过服务器的时间？
改的好像是UTC时区的时间，现在时区改成香港的+0800，时间也调整了

**Comment by zerolocker** [comment]
没有，我是没有权限的

## 

Best regards,
刘卓德
Shenzhen University
Class of 2015
College of Computer Science and Software Engineering

在 2014-06-07 12:41:20，"Tao Li" notifications@github.com 写道：

BTW， @zerolocker 你是不是改过服务器的时间？
改的好像是UTC时区的时间，现在时区改成香港的+0800，时间也调整了

**Comment by Eroica-cpp** [comment]
报错：

> Caused by: java.net.BindException: 地址已在使用
>        at java.net.PlainSocketImpl.socketBind(Native Method)
>        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
>        at java.net.ServerSocket.bind(ServerSocket.java:376)
>        at java.net.ServerSocket.<init>(ServerSocket.java:237)
>        at java.net.ServerSocket.<init>(ServerSocket.java:181)
>        at org.eclipse.jetty.server.bio.SocketConnector.newServerSocket(SocketConnector.java:96)
>        at org.eclipse.jetty.server.bio.SocketConnector.open(SocketConnector.java:85)
>        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
>        at org.eclipse.jetty.server.bio.SocketConnector.doStart(SocketConnector.java:156)
>        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>        at org.eclipse.jetty.server.Server.doStart(Server.java:291)
>        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1259)
>        at java.security.AccessController.doPrivileged(Native Method)
>        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1182)

这是因为socket的端口被占用？如果没有别的东西在跑，我重启一下服务器

**Comment by Eroica-cpp** [comment]
重启了服务器，现在知道问题了。
服务器端的配置文件没有更新到最新版本，导致IK中文分词jar没法加载 。
现在的最新版本的配置文件还是有一点问题，先无视这个好了。

**Comment by Eroica-cpp** [comment]
更新一下，我重新整理了爬出来的文件，发现最早的公文通是2002年发的，在[这里](http://www.szu.edu.cn/board/view.asp?id=65254)。13年间一共有69575篇公文通。
