### ISSUE TITLE
求计算文本相似度

### ISSUE THREAD

**Issue by Eroica-cpp** [Eroica-cpp/DistSearch#7]
@zerolocker @fengwuxing 

key_word_dict.pickle文件我已经传到了服务器~/目录下

在python中读取pickle文件的方法:

``` python
import cPickle
f = open("key_word_dict.pickle")
key_word_dict = cPickle.load(f)
```

这样就得到了python中的一个dictionary对象key_word_dict，方便使用！
这个dictionary的key是id, value是关键字列表，已经根据重要程度降序排列，用的时候截取前一部分即可。

**Comment by zerolocker** [comment]
李焘谈到知道所有点两两之间的距离组成的距离矩阵D ，并且给定所有点的所属的cluster的类的编号， 能不能为每一个类找到它的重心， 这个重心是一种特殊的重心， 它是离真正的重心最近的那个点。
解决这个问题可以加快 k-means 找cluster centroid的速度。

对于这个问题，有这个解决办法：
有一个定理说“三角形的重心到3个点的距离平方和最短”，我发现，这个定理可以推广到多个点、多个维的情形。也就是
    如果使用欧几里得距离，那么有这个定理：重心是到所有点距离的平方和最小的那个点。
然后这条定理就可以解决这个问题了， 方法是算出距离矩阵D中每一行平方和，然后按每个cluster分组，找出每个类的最小值。
我不知道使用除了欧几里得距离之外的距离函数能不能有这个好处。
数院大神焘哥有空不妨证明一下别的距离函数 哈哈

## 

Best regards,
刘卓德
Shenzhen University
Class of 2015
College of Computer Science and Software Engineering

在 2014-06-10 01:13:36，"-Tao Li" notifications@github.com 写道：

@zerolocker@fengwuxing

key_word_dict.pickle文件我已经传到了服务器~/目录下

在python中读取pickle文件的方法:

importcPicklef=open("key_word_dict.pickle")key_word_dict=cPickle.load(f)

这样就得到了python中的一个dictionary对象key_word_dict，方便使用！
这个dictionary的key是id, value是关键字列表，已经根据重要程度降序排列，用的时候截取前一部分即可。

**Comment by Eroica-cpp** [comment]
刚刚在车上用github手机客户端给坑了，写了一大推发了一个空的。。。。

其实不需要欧几里得距离的，切比雪夫距离就可以了（比较装逼的说法，其实就是绝对值）

我想到了一个改进的办法：
之前讨论的是把每两个结点的距离算出来，然后存到hash table里面，形成很多对(id1, id2, distance)
 现在想到的办法存储(id, ranked_list), 其中ranked_list 是前k个最近的点(比如k=20)，好处是省去每次迭代的时候要对所有的点重新遍历一遍，直接查表就好了。同时还有存储空间的好处，假设有N个id,那么之前的方法要存储N_N个值， 现在只需要存储k_N个值就行了(k << N)。
当然这样损失了一些信息，直观上讲距离远的点影响也不大, 得到的结果甚至可能是无偏估计。

关于如何求centroid。 中心的直观含义就是距离这一类中所有的点都比较近的点，那么这个点在众多的ranked_list中的排名应该比较前的， 对每个点在众多ranked_list中求秩和，秩和最小的点可以认为是中点。这个只需要整数运算，比浮点运算应该又能快一些。

**Comment by Eroica-cpp** [comment]
计软大神@zerolocker 神速！
明天请教一些问题

**Comment by zerolocker** [comment]
跟我在上一个留言里面说的的方法比较， 你说的求rank和的区别是：
①我的方法是对每一个点，把它到所有其他店的距离的平方和求出来， 你的是对每一个点，把它在所有点中的rank和求出来，这样等同于作了一个近似：把实数距离离散化为rank,即 1,2,3，。。。 而且无论远近，只要rank相同，距离都相同。
②我的方法是考虑所有点， 你的方法只考虑最近的前k个点， 这样也等于作了近似。

在这两个近似下， 得出来的centroid还会准吗？

另外一个问题就是，如果你只考虑前k个点， 那么有些点排在k之外，按你的计算方式，它们到当前点的距离相当于是0。这样也不妥当。
（比如说有个点排在所有点的top-k之外，那么它的rank和就是0，那这个点就很NB了，它到所有点都是最近的。）

## 

Best regards,
刘卓德
Shenzhen University
Class of 2015
College of Computer Science and Software Engineering

在 2014-06-10 06:26:44，"Tao Li" notifications@github.com 写道：

刚刚在车上用github手机客户端给坑了，写了一大推发了一个空的。。。。

其实不需要欧几里得距离的，切比雪夫距离就可以了（比较装逼的说法，其实就是绝对值）

我想到了一个改进的办法：
之前讨论的是把每两个结点的距离算出来，然后存到hash table里面，形成很多对(id1, id2, distance)
现在想到的办法存储(id, ranked_list), 其中ranked_list 是前k个最近的点(比如k=20)，好处是省去每次迭代的时候要对所有的点重新遍历一遍，直接查表就好了。同时还有存储空间的好处，假设有N个id,那么之前的方法要存储N_N个值， 现在只需要存储k_N个值就行了(k << N)。
当然这样损失了一些信息，直观上讲距离远的点影响也不大, 得到的结果甚至可能是无偏估计。

关于如何求centroid。 中心的直观含义就是距离这一类中所有的点都比较近的点，那么这个点在众多的ranked_list中的排名应该比较前的， 对每个点在众多ranked_list中求秩和，秩和最小的点可以认为是中点。这个只需要整数运算，比浮点运算应该又能快一些。

**Comment by Eroica-cpp** [comment]
邮箱发送的排版有点问题，重新排版：

### 第一个问题

> 我的方法是对每一个点，把它到所有其他店的距离 的平方和求出来， 你的是
> 对每一个点，把它在所有点中的rank和求出来，这样等同于作了一个近似：把
> 实数距离离散化为rank,即 1,2,3，。。。 而且无论远近，只要rank相同，距
> 离都相同。

这种方法不是我的原创，是非参数统计的想法，没有利 用到具体数值，只是利用 
秩，少了一些信息，但是也有如下好处：
1. 稳健。 数据中有很多异常的点，所谓的具体数值也是通过特征提取出来的，对具体数据过于敏感可能引入更多的噪声；现在这种方法在这点上比较好。
2. 高效。显然这种求rank的方法比求欧式距离的方法要高效一些。

在对真实的数据测试之前，很难说那种方法更好。这个 只是一种想法。

### 第二个问题

> 我的方法是考虑所有点， 你的方法只考虑最近的前k个点， 这样也等于作了
> 近似。

效率和准确率的 trade-off, 用 top k代替了整个list，某种程度上相当于提取了 
主成分。
从intuition的角度来说，排在ranked_list后面的点（也就是距离很远的点）没有 
必要考虑吧
效果还是要看测试结果，很难说。这个也算小的创新点了。

### 第三个问题

> 另外一个问题就是，如果你只考虑前k个点， 那么有些点排在k之外，按你的
> 计算方式，它们到当前点的距离相当于是0。这样也不妥当。
> （比如说有个点排在所有点的top-k之外，那么它的rank和就是0，那这个点就
> 很NB了，它到所有点都是最近的。）

排在k之外的点当然认为是Inf了，当然Inf不好 编程实现(设定一个很大的常数也 
会有问题)，所有在k之外的点的rank全部认为是k+1就行了。
