### ISSUE TITLE
关于最后的展示，发现个好东西！

### ISSUE THREAD

**Issue by Eroica-cpp** [Eroica-cpp/DistSearch#9]
@zerolocker @fengwuxing 

github上一个开源的项目[impress.js](https://github.com/bartaz/impress.js)，用来做幻灯片，效果酷毙，效果看这里：[http://bartaz.github.io/impress.js/#/overview](http://bartaz.github.io/impress.js/#/overview)

最后的展示就这么做了！

**Comment by Eroica-cpp** [comment]
@zerolocker @fengwuxing 

不得不说github真是个好东西，每一个repo给一个二级域名，内容完全自己定制，可以嵌入js代码; 
于是乎我搭了一个项目主页：[http://eroica-cpp.github.io/campus-search-engine/](http://eroica-cpp.github.io/campus-search-engine/)。

现在项目主页上挂的东西是impress.js的一个实例，可以代替ppt, 而且效果炫很多。
(现在基本照搬这个网站的[http://www.hashdog.com/brochure/](http://www.hashdog.com/brochure/)， 只是首页改了一改。这里两天我想在这个模板上塞东西，现在比较挫。。。不喜勿喷。。)

我们最后展示的时候，根本不需要U盘这种东西，上台什么都不带，
直接打开浏览器输入url就可以了，高端洋气有木有！！

@fengwuxing 做首页其实可以“偷”别的网站，直接右键另存为只能存html文档，动态的脚本存不下来(因为要运行)，有时候一些图片也没有了 :(
发现一个神器[HTTrack Website Copier](http://www.httrack.com/), 直接生成网站的镜像到本地，相当好用。而且操作是图形界面的。

**Comment by fengwuxing** [comment]
1、这里http://bartaz.github.io/impress.js/#/overview 的效果我看着有点晕，不知道有没有更加好的。
2、那个php中的中文乱码问题，我已经解决了，接下来就是前端的页面样式的设计问题了。各位有什么想法吗？只是和百度的差不多？
3、我知道可以偷别的网页，但是目前可以偷哪个的。神器HTTrack Website Copier我去了解一下。对了，第一次发issues，怎么内嵌超链接？

**Comment by Eroica-cpp** [comment]
@fengwuxing  Congrat!! 发issue很容易吧

> 1、这里http://bartaz.github.io/impress.js/#/overview 的效果我看着有点晕，不知道有没有更加好的。

看看现在用的模板怎么样？
[http://eroica-cpp.github.io/campus-search-engine/](http://eroica-cpp.github.io/campus-search-engine/)

> 2、那个php中的中文乱码问题，我已经解决了，接下来就是前端的页面样式的设计问题了。各位有什么想法吗？只是和百度的差不多？

well done!
之前我发现一个boostrap的搜索引擎模板，感觉还不错，我去找找看。

> 3、我知道可以偷别的网页，但是目前可以偷哪个的。神器HTTrack Website Copier我去了解一下。对了，第一次发issues，怎么内嵌超链接？

发超链接的格式

```
[标题](url)
```

比如下面的代码：

```
[百度](www.baidu.com)
```

生成的效果就是：
[百度](www.baidu.com)

**Comment by Eroica-cpp** [comment]
我觉得比较理想的是首页有一个about的按钮，点击可以跳转到演示的幻灯片（时间紧就算了，现在已经做的足够多了）。

-》这个没有问题啊，我们展示地址是[http://eroica-cpp.github.io/campus-search-engine/](http://eroica-cpp.github.io/campus-search-engine/)吧，加一个链接很容易的。

还有一个小问题是上面的js效果IE是不支持的，chrome firefox没问题。

-》展示的时候不使用IE就好了，这个没有问题。

**Comment by zerolocker** [comment]
卧槽！ HTTrack Website Copier 神器来的，你们有没有试过？
